name: Build Once Time

env:
  RUST_VERSION: stable
  REGISTRY: docker.io
  IMAGENAME: initdc/rust-demo

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set Rust version  
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '${{ env.RUST_VERSION }}'
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Extract Docker metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGENAME }}  
      - name: Set RELEASE_VERSION
        run: |
          set -e
          
          RELEASE_VERSION="${GITHUB_REF##*/}"
          if [[ "${RELEASE_VERSION}" != v* ]]; then RELEASE_VERSION='dev'; fi
          echo RELEASE_VERSION="${RELEASE_VERSION}" >> $GITHUB_ENV      
      - name: Build release
        run: |
          ruby build.rb --install-cc
          ruby build.rb ${RELEASE_VERSION}
      - name: Generate SHA256SUM
        run: ruby sha256sum.rb upload SHA256SUM-linux
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-build-artifacts
          path: "upload/*"
      - name: Upload to Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "upload/*"
      - name: Build and push Docker image
        run: ruby docker-tag.rb ${RELEASE_VERSION}
