name: Merge or Pull requests

env:
  RUST_VERSION: stable

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'
      - 'next'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Rust version  
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '${{ env.RUST_VERSION }}'
      - name: Build Artifact
        run: |
          ruby build.rb --install-cc
          ruby build.rb test
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: "upload/*"