name: Merge or Pull requests

env:
  RUST_VERSION: stable

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'
      - 'next'
  pull_request:

concurrency: 
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Rust version  
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '${{ env.RUST_VERSION }}'
      - name: Build Artifact
        run: |
          ruby build.rb --install-cc
          ruby build.rb test
      - name: Generate SHA256SUM
        run: ruby sha256sum.rb upload SHA256SUM-linux    
      - name: Clone my upload-artifact
        run: git clone https://github.com/initdc/upload-artifact.git ./upload-artifact
      - name: Upload Artifact
        uses: ./upload-artifact
        with:
          path: "upload/*"
          artifact-per-file: true