# ref: https://github.com/rust-lang/rustup/blob/master/ci/actions-templates/windows-builds-template.yaml
name: Build On Windows
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    branches:
      - 'dev'
      - 'next'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-pc-windows-msvc
          - i686-pc-windows-msvc
          - aarch64-pc-windows-msvc
          - x86_64-pc-windows-gnu
          - i686-pc-windows-gnu
        include:
          - target: x86_64-pc-windows-gnu
            mingw: https://ci-mirrors.rust-lang.org/rustc/x86_64-6.3.0-release-posix-seh-rt_v5-rev2.7z
            mingwdir: mingw64
          - target: i686-pc-windows-gnu
            mingwdir: mingw32
            mingw: https://ci-mirrors.rust-lang.org/rustc/i686-6.3.0-release-posix-dwarf-rt_v5-rev2.7z
          - target: aarch64-pc-windows-msvc 
            skip_tests: yes 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install mingw
        if: matrix.mingw != ''
        run: |
          # We retrieve mingw from the Rust CI buckets
          # Disable the download progress bar which can cause perf issues
          $ProgressPreference = "SilentlyContinue"
          Invoke-WebRequest ${{ matrix.mingw }} -OutFile mingw.7z
          7z x -y mingw.7z -oC:\msys64 | Out-Null
          del mingw.7z
          echo "C:\msys64\usr\bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
          echo "C:\msys64\${{ matrix.mingwdir }}\bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
        shell: powershell
      - name: Set environment variables appropriately for the build
        run: |
          echo "%USERPROFILE%\.cargo\bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
          echo "TARGET=${{ matrix.target }}" | Out-File -Append -FilePath $env:GITHUB_ENV -Encoding utf8
          echo "SKIP_TESTS=${{ matrix.skip_tests }}" | Out-File -Append -FilePath $env:GITHUB_ENV -Encoding utf8
      - name: Ensure stable toolchain is up to date
        run: rustup update stable
      - name: Install the target
        run: |
          rustup target install ${{ matrix.target }}
      - name: Run a full build & Dump dynamic link targets
        run: |
          cargo build --release --target="${env:TARGET}"
          mkdir upload
          copy target\${env:TARGET}\release\rust-demo.exe upload\${env:TARGET}
        shell: powershell 
      - name: Generate SHA256SUM
        run: ruby sha256sum.rb upload SHA256SUM-${env:TARGET}
        shell: powershell   
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-build-artifacts
          path: "upload/*"
      - name: Upload to Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "upload/*"
